stages:
  - test
  - egg
  - test_egg
  - deploy

variables:
  SONAR_SCANNER: sonar-scanner -Dsonar.host.url=http:sonar.contact.de:9000

.linux_tox: &linux_tox
  image: "themattrix/tox"
  tags:
    - Docker

.windows_tags: &win_tags
  tags:
    - Windows

.python2: &python2-alpine
  image: python:2.7-alpine
  tags:
    - Docker

.python2: &python2
  image: python:2.7
  tags:
    - Docker

.python3: &python3
  image: python:3.5
  tags:
    - Docker

#------------------------------
# Test stage
#------------------------------

.test:
  script: "tox"
  stage: test
  artifacts:
    when: on_success
    paths:
    - ./coverage-py*.xml
    expire_in: 1 day

linux:
  <<: *linux_tox
  extends: .test
  variables:
    CI_OS: "linux"

windows:
  <<: *win_tags
  extends: .test
  variables:
    CI_OS: "windows"
  allow_failure: true

#------------------------------
# Egg building stage
#------------------------------
build:
  <<: *python2-alpine
  stage: egg
  before_script:
    - apk add g++ linux-headers make python3 python3-dev py3-sphinx
    - python -m pip install wheel psutil
    - python3 -m pip install wheel psutil python-dateutil sphinxcontrib-fulltoc
  script: "make pack"
  artifacts:
    paths:
      - ./dist/*.egg
      - ./dist/*.whl
      - ./doc/pyperf/html/*
    expire_in: 1 day

.analyze: &analyze
  stage: egg
  image: registry.contact.de/gitlab-sonar-scanner
  tags:
    - Docker
  script:
    - pylint pyperf --rcfile=.pylintrc --disable=similarities --persistent=no -rn -sn > pylint-report.txt || true
    - $SCAN

analyze_branch:
  <<: *analyze
  variables:
    SCAN: $SONAR_SCANNER -Dsonar.analysis.mode=preview
  except:
    - master
    - tags

analyze:
  <<: *analyze
  variables:
    SCAN: $SONAR_SCANNER -Dsonar.analysis.mode=publish
  only:
    - master
    - tags

#------------------------------
# Egg testing stage
#------------------------------
.test_egg: &test_egg
  stage: test_egg
  script:
    - mkdir reports
    - $PYTHON -m pyperf run -o pyperf-report.json -s pyperf-benchsuite.json
    - $PYTHON -m pyperf upload pyperf-report.json --url http://influxdb.contact.de:8086 --tags="Python-Version:$PY_VERSION","installed-from:$INSTALLED_FROM","branch:$CI_COMMIT_REF_NAME"

test_python2_egg:
  <<: *python2
  <<: *test_egg
  variables:
    PYTHON: python
    PY_VERSION: 2
    INSTALLED_FROM: "egg"
  before_script:
    - python -m easy_install dist/pyperf-*-py2.7.egg

test_python2_wheel:
  <<: *python2
  <<: *test_egg
  variables:
    PYTHON: python
    PY_VERSION: 2
    INSTALLED_FROM: "whl"
  before_script:
    - python -m pip install dist/pyperf-*-py2-none-any.whl

test_python3_wheel:
  <<: *python3
  <<: *test_egg
  variables:
    PYTHON: python3
    PY_VERSION: 3
    INSTALLED_FROM: "whl"
  before_script:
    - python3 -m pip install dist/pyperf-*-py3-none-any.whl


#------------------------------
# Deployment stage
#------------------------------
.upload: &upload
  <<: *python2-alpine
  stage: deploy
  before_script:
    - apk add --upgrade make python python-dev py-pip g++ libffi-dev
    - python -m pip install devpi
  script:
    - make upload

dry-run-upload:
  <<: *upload
  variables:
    ARMED: "False"
  except:
    - tags

upload:
  <<: *upload
  variables:
    ARMED: "True"
  only:
    - tags

pages:
  image: alpine
  stage: deploy
  tags:
    - Docker
  script:
    - mv doc/pyperf/html public
  artifacts:
    paths:
      - public
  only:
    - tags
